### PR TITLE
Synchronize Tag Colors

### LINKED ISSUE #73: Synchronize Tag Colors
**Is your feature request related to a problem? Please describe.**
Use tag colors from server in the app.

**Describe the solution you'd like**

- I had to update to the API version 2 as described [here](https://paperless-ng.readthedocs.io/en/latest/api.html#api-versioning)
- I added tag color and text_color data
- Removed the OgTag class (don't know if it is still required)

Actually, in my opinion your approach for the text color of the tags `(ThemeData.estimateBrightnessForColor(getColor()) == Brightness.light)` seems to work a bit better than the code from Paperless-ngx, maybe you should omit changing `getTextColor()`.

```diff
   Color getTextColor() {
-    if (ThemeData.estimateBrightnessForColor(getColor()) == Brightness.light)
-      return Colors.black;
-    return Colors.white;
+    return _fromHex(tag.textColor!);
   }
```

### PR DESCRIPTION
**Pull request by BeneGrueter**
fixes #73 

As mentioned in #73 , maybe changing `getTextColor`should be omitted.

### CODE REVIEW

**Comment by bauerj** [comment]
Hey,

thanks for your PR! 

Some notes on your implementation:

- We probably need to break support with OG Paperless eventually but it's not necessary for this PR. Could you please leave that in?
- The API versioning scheme is a bit more complex: https://github.com/jonaswinkler/paperless-ng/blob/05c36f91cfa5613bdea5b3c490774cc40b586eeb/docs/api.rst#api-versioning The app needs to fall back to API version 1 for older servers. So, by default it should request V2, if the server says it's unsupported, request again with v1. 

We should probably start nagging users to upgrade their servers from pre 1.3-ng and especially from -og. But we can't break support yet since those versions are still in use.

So we need to have three tag implementations:

1. OgTag for OG paperless
2. TagV1 for -ng API version 1
3. Tag for the current implementation

All of those, of course, need to provide the same interface, either through JSON transforms or a getter method.

As you see this is a lot more complicated than it should be ☹️ Do you want to change this PR to allow backwards compatibility?

**Comment by BeneGrueter** [comment]
Ahh yes that makes sense - thanks for the hints! I will look into it when I find the time 👍

**Comment by BeneGrueter** [comment]
After understanding the code a bit better I now think you have already made all required changes in 0689ea13f6f51566855d5be940725ddd74c607f9 , could this be correct?

I think you predicted the changed json key to be `colour_code` but it ended up being just `color`. OG paperless and API version 1 both seem to work with the OgTag implementation. The only other required change was adapting the API version.

Everything is working with paperless ngx and paperless ng version 1.2 and version 1.3, however I'm not sure about OG paperless as mentioned in the review. I will try to get a test running if you don't have it readily available

**Comment by BeneGrueter** [comment]
> Everything is working with paperless ngx and paperless ng version 1.2 and version 1.3, however I'm not sure about OG paperless as mentioned in the review. I will try to get a test running if you don't have it readily available

got it to work in OG paperless as well now

**Pull request merged**
