### PR TITLE
set usesCleartextTraffic to true

### PR DESCRIPTION
**Pull request by qcasey**
I think this is all we need.

That being said I can't replicate #28 with any release I build myself, it only happens on @bauerj current releases. Makes me think it's my dev environment. I'm going to build this in a vm and will see if that changes anything.

I can create a new release if you'd like, or would you like to wait on that?

### CODE REVIEW

**Comment by bauerj** [comment]
I think it might be allowed for debug builds by default. Or did you try it with a release build?

Anyway, feel free to create a new release.

**Comment by qcasey** [comment]
Even my own signed release builds of 0.0.8 didn't have this problem. Oh well, I'll go ahead anyway.

**Comment by bauerj** [comment]
Oh well, it's fixed either way 😄

I'll test it on my PC when I'm back home but I guess this should work. Are you on the latest Flutter SDK version?

**Comment by qcasey** [comment]
Yep :man_shrugging: guess it doesn't really matter, just a little annoying
```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (13 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

**Comment by qcasey** [comment]
Tried releasing on Google Play but got the below message. I think it's because we're using different signing `key.jks`.

It's no big deal, it can absolutely wait till after Christmas. Have a good one :+1: 

```
You uploaded an APK that is signed with a different certificate to your previous APKs. You must use the same certificate. Your existing APKs are signed with the certificate(s) with fingerprint(s):

SHA1: C4:F3:F0:CB:4B:81:18:4A:85:4B:9C:C4:0B:C9:8D:7E:C3:2A:76:56

and the certificate(s) used to sign the APK you uploaded have fingerprint(s):

SHA1: 32:B3:79:BD:69:65:C7:4B:3C:EE:3D:C2:51:5E:88:44:C2:AD:84:DC
```

**Comment by bauerj** [comment]
Oh right, I forgot! I'll send it to you soon.

Nice Christmas to you as well!

**Pull request merged**
